### ISSUE TITLE
Puma 6.0.0

### ISSUE THREAD

**Issue by JerrodCarpenter** [yob/puma-plugin-statsd#43]
Happy to contribute here, but noticed we have `< 6` in our gemspec. Is there an expected issue with the Puma upgrade? What can I do to help?

**Comment by danarnold** [comment]
It seems to me that the only incompatibility is the [change in puma's internal logging syntax](https://github.com/puma/puma/pull/2798).

Making [these changes](https://github.com/cacheventures/puma-plugin-statsd/commit/48c6360178b51ed53e3b2f9f806e493c0423e717) will fix the incompatibility in the simplest way. However, these changes aren't backwards compatible (which is why I changed my fork's gemspec to only allow version 6.x). For backwards compatibility, it's probably better to implement something [like appsignal did](https://github.com/appsignal/appsignal-ruby/commit/2ba10805240afd1ce472e4705c20524961b5ce2f) to allow logging with either the old or the new syntax.

**Comment by tricknotes** [comment]
@yob 
How do you think about this topic?
If is OK to drop Puma < 6, @danarnold 's change seems good.
However, to keep older version, we need more commits.

**Comment by tricknotes** [comment]
@danarnold 
Could you send a PR?
It is good place to discuss this approach.

**Comment by danarnold** [comment]
I'm happy to create a PR if project maintainers wish it, but as of now I'd just be copying over my comments here to there, so I don't really see the benefit.

**Comment by yob** [comment]
To ease the transition for users between puma 5/6 I'd prefer to keep support for both versions for some time in the 2.x series, and eventually (at least a year or more) release a 3.x series that drops support for puma 5.x.

We're not using puma 6 at my dayjob yet so this incompatibility hasn't come up, but I'll happily accept a PR that adds puma 5+6 compatibility and release 2.4.0.

**Comment by tricknotes** [comment]
@yob @danarnold 
Thanks for your response.
I made a PR for this issue. https://github.com/yob/puma-plugin-statsd/pull/46

Could you review this, all?
